# Generated by Django 5.0.6 on 2024-06-13 15:46

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limupapp', '0002_subcategory_subsubcategory_category_sub_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('text', ckeditor.fields.RichTextField()),
                ('btn_text', models.CharField(max_length=50)),
                ('btm_url', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slider_item', models.ManyToManyField(to='limupapp.slideritem')),
            ],
        ),
    ]
