# Generated by Django 5.0.6 on 2024-06-14 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('limupapp', '0003_slideritem_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImgs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pd_imgs', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('product_type', models.CharField(choices=[('FEATURED', 'FEATURED'), ('RAGULAR', 'RAGULAR')], max_length=20)),
                ('regular_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('offer_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount_percentage', models.FloatField(blank=True, null=True)),
                ('is_hot_deal', models.BooleanField(default=False)),
                ('hot_deal_date', models.DateField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('stock_quantity', models.PositiveIntegerField()),
                ('slug', models.SlugField(unique=True)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('long_description', models.TextField(blank=True, null=True)),
                ('thumbnail_image', models.ImageField(upload_to='thumbnails/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='limupapp.category')),
                ('gallery_images', models.ManyToManyField(to='products.galleryimgs')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='limupapp.subcategory')),
                ('sub_sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='limupapp.subsubcategory')),
            ],
        ),
    ]
